name: task-app-actions
run-name: task-app 🚀
on:
  push:
    branches:
      - master
env:
  CD_DEFAULT_BRANCH: master
jobs:
  task-app-gitHub-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Start ssh connexion
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CD_HOST }}
          username: ${{ secrets.CD_USERNAME }}
          key: ${{ secrets.SSH_VPS_PRIVATE_KEY }}
          script: |
            cd task-app 
            eval $(ssh-agent -s) && ssh-add <(echo "${{ secrets.SSH_GITHUB_PRIVATE_KEY }}")
            git fetch origin 
            git reset --hard origin/${{ env.CD_DEFAULT_BRANCH }}
            npm ci
            npm run build
            pm2 restart ecosystem.config.js --env production
            pm2 save
