name: task-app-actions
run-name: task-app 🚀
on:
  push:
    branches:
      - master
jobs:
  task-app-gitHub-actions:
    runs-on: ubuntu-latest
    steps:
      - run: ssh ${{ secrets.CD_HOST }}
      - run: eval `ssh-agent -s` && ssh-add  ${{ secrets.SSH_PRIVATE_PATH }}
      - run: cd task-app && git fetch origin && git pull && npm ci && npm run build && pm2 restart ecosystem.config.js --env production && pm2 save
